# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      workingDirectory: '$(system.defaultWorkingDirectory)'
      tasks: 'assembleRelease'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false

#  - task: AndroidSigning@2
#    inputs:
#      apkFiles: '**/*.apk'
#      jarsign: true
#      jarsignerKeystoreFile: 'pathToYourKeystoreFile'
#      jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
#      jarsignerKeystoreAlias: 'yourKeystoreAlias'
#      jarsignerKeyPassword: '$(jarsignerKeyPassword)'
 #     zipalign: true
  
  - task: CopyFiles@2
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'
#  - task: PublishBuildArtifacts@1
  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: '75658a38-70b1-453c-9978-381adbe7e772/4cd39f36-934b-47c6-83aa-8200c60b5f6e'
      vstsFeedPackagePublish: 'keychain-chat-android'
      versionOption: 'patch'
      packagePublishDescription: 'Consumer application for JCB Micro Densai'
#  - task: GooglePlayRelease@2
#    inputs:
#      apkFile: '**/*.apk'
#      serviceEndpoint: 'yourGooglePlayServiceConnectionName'
#      track: 'internal'